#!/bin/bash

# Error checks
if [ -z "$1" ]; then
    echo "USAGE: ./newcmd NAME_OF_COMMAND"
    exit
fi

# Check for existing file
if [ -d "$1" ]; then
    echo "Command $1 already exists. Not overwriting."
    exit
fi

# Make appropriate directory and copy template
mkdir $1
cp template.js ./$1/index.js

# Replace necessary text in template
sed -i 's/REPLACEME/'$1'/g' ./$1/index.js